# Generated by Django 3.2.5 on 2021-11-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='vegetables',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
