# Generated by Django 3.2.5 on 2021-11-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_usermodel_vegetables'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='access',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='adobe_acrobate',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='amc_end_date',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='amc_start_date',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='antivirus',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='asset_no',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='autocad',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='domain_workgoup',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='emp_id',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='gef_id_number',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='hdd',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='location',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='machine_model_no',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='machine_type',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='make1',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='make2',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='model',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='ms_office_version',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='oem',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='os',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='os_version',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='processor_purchase_date',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='ram',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='remarks',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='sap',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='serial_no1',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='serial_no2',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='status',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='usage_type',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_acceptance_date',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_handed_over_date',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='visio',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='warranty_end_date',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
